

import sys
import os
import pytest
import numpy as np
import pandas as pd

# Resolve src path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from src.data_loader import preprocess, build_trader_summary, get_sentiment_summary
from src.hypothesis_tests import kruskal_wallis_test, spearman_correlation_test, pairwise_mannwhitney
from src.ml_model import build_feature_matrix, train_and_evaluate
from src.insights import compute_key_stats, RECOMMENDATIONS


# ── Fixtures ──────────────────────────────────────────────────────────────────

@pytest.fixture(scope="module")
def raw_data():
    """Load the generated CSVs (generated by data/generate_data.py)."""
    data_dir = os.path.join(os.path.dirname(__file__), "..", "data")
    trades_path = os.path.join(data_dir, "trades.csv")
    fg_path     = os.path.join(data_dir, "fear_greed.csv")
    if not os.path.exists(trades_path) or not os.path.exists(fg_path):
        pytest.skip("Data files not found. Run data/generate_data.py first.")
    trades = pd.read_csv(trades_path, parse_dates=["timestamp"])
    fg     = pd.read_csv(fg_path, parse_dates=["date"])
    return trades, fg


@pytest.fixture(scope="module")
def processed(raw_data):
    trades, fg = raw_data
    return preprocess(trades, fg)


# ── Data loading tests ────────────────────────────────────────────────────────

class TestDataLoading:
    def test_trades_shape(self, raw_data):
        trades, _ = raw_data
        assert len(trades) == 20_000, "Expected 20,000 trade rows."

    def test_fg_length(self, raw_data):
        _, fg = raw_data
        assert len(fg) >= 480, "Expected ~500 Fear & Greed rows."

    def test_trades_columns(self, raw_data):
        trades, _ = raw_data
        required = {"account", "symbol", "closedPnL", "leverage", "size"}
        assert required.issubset(set(trades.columns))

    def test_no_duplicate_timestamps(self, raw_data):
        trades, _ = raw_data
        # Trades can share a timestamp but the (timestamp, account, symbol) triple should not
        dups = trades.duplicated(subset=["timestamp", "account", "symbol", "side"])
        assert dups.sum() / len(trades) < 0.01, "Too many duplicate entries."


# ── Preprocessing tests ───────────────────────────────────────────────────────

class TestPreprocessing:
    def test_is_winner_binary(self, processed):
        assert processed["is_winner"].isin([0, 1]).all()

    def test_sentiment_categories(self, processed):
        expected = {"Extreme Fear", "Fear", "Neutral", "Greed", "Extreme Greed"}
        actual   = set(processed["sentiment"].unique())
        assert actual.issubset(expected)

    def test_hour_range(self, processed):
        assert processed["hour"].between(0, 23).all()

    def test_leverage_bucket_present(self, processed):
        assert "leverage_bucket" in processed.columns

    def test_no_null_pnl(self, processed):
        assert processed["closedPnL"].isna().sum() == 0

    def test_trader_summary_columns(self, processed):
        summary = build_trader_summary(processed)
        for col in ["total_pnl", "win_rate", "avg_leverage", "trade_count"]:
            assert col in summary.columns

    def test_sentiment_summary_regimes(self, processed):
        ss = get_sentiment_summary(processed)
        assert len(ss) == 5, "Expected 5 sentiment regimes in summary."


# ── Statistical tests ─────────────────────────────────────────────────────────

class TestHypothesisTests:
    def test_kw_returns_dict(self, processed):
        result = kruskal_wallis_test(processed)
        assert "statistic" in result and "p_value" in result

    def test_kw_p_value_range(self, processed):
        result = kruskal_wallis_test(processed)
        assert 0.0 <= result["p_value"] <= 1.0

    def test_spearman_rho_range(self, processed):
        result = spearman_correlation_test(processed)
        assert -1.0 <= result["statistic"] <= 1.0

    def test_pairwise_mw_shape(self, processed):
        pw = pairwise_mannwhitney(processed)
        # C(5,2) = 10 pairs
        assert len(pw) == 10

    def test_pairwise_mw_columns(self, processed):
        pw = pairwise_mannwhitney(processed)
        for col in ["group_1", "group_2", "p_value", "p_bonferroni"]:
            assert col in pw.columns


# ── ML model tests ────────────────────────────────────────────────────────────

class TestMLModel:
    def test_feature_matrix_shape(self, processed):
        X, y, names = build_feature_matrix(processed)
        assert X.shape[0] == y.shape[0]
        assert X.shape[1] == len(names)
        assert len(names) >= 4

    def test_target_binary(self, processed):
        _, y, _ = build_feature_matrix(processed)
        assert set(np.unique(y)).issubset({0, 1})

    def test_cv_auc_in_range(self, processed):
        results = train_and_evaluate(processed, n_estimators=50, cv_folds=3)
        auc = results["cv_auc_mean"]
        assert 0.45 <= auc <= 0.65, f"CV AUC {auc} out of expected range."

    def test_importances_sum_to_one(self, processed):
        results = train_and_evaluate(processed, n_estimators=50, cv_folds=3)
        total = sum(results["importances"].values())
        assert abs(total - 1.0) < 0.01

    def test_fg_in_top4_features(self, processed):
        """FG index should rank in top 4 (consistent with report's 3rd place finding)."""
        results = train_and_evaluate(processed, n_estimators=50, cv_folds=3)
        ranked  = sorted(results["importances"], key=results["importances"].get, reverse=True)
        fg_col  = next(c for c in ranked if "fg" in c.lower() or "value" in c.lower())
        assert ranked.index(fg_col) < 4, f"FG index ranked {ranked.index(fg_col)+1}, expected top 4."


# ── Insights tests ────────────────────────────────────────────────────────────

class TestInsights:
    def test_recommendations_count(self):
        assert len(RECOMMENDATIONS) == 6

    def test_recommendations_fields(self):
        for rec in RECOMMENDATIONS:
            for field in ["id", "title", "action", "priority"]:
                assert field in rec, f"Missing field '{field}' in recommendation {rec.get('id')}"

    def test_key_stats(self, processed):
        trader_df = build_trader_summary(processed)
        stats = compute_key_stats(processed, trader_df)
        assert 0 < stats["pct_profitable_traders"] < 100
        assert stats["low_leverage_win_rate"] >= stats["high_leverage_win_rate"] - 20


# ── Smoke test: full pipeline ─────────────────────────────────────────────────

class TestFullPipeline:
    def test_end_to_end_no_crash(self, raw_data, tmp_path):
        from src.eda import plot_master_dashboard, plot_deep_dive
        trades, fg = raw_data
        df         = preprocess(trades, fg)
        trader_df  = build_trader_summary(df)
        results    = train_and_evaluate(df, n_estimators=20, cv_folds=2)
        importances = results["importances"]

        # Dashboard should save without error
        plot_master_dashboard(df, trader_df, importances, str(tmp_path / "fig1.png"))
        plot_deep_dive(df, trader_df, fg, str(tmp_path / "fig2.png"))
        assert (tmp_path / "fig1.png").exists()
        assert (tmp_path / "fig2.png").exists()
